### ISSUE TITLE
PaleMoon and Gentoo Hardened

### ISSUE THREAD

**Issue by Kalle72** [deuiore/palemoon-overlay#18] opened 2016-03-04 14:09 UTC
Hello,

Thanks for bringing PaleMoon to Gentoo!!! 

I have a problem to compile PaleMoon and think that it is related to my usage of Gentoo Hardened (hardened-kernel with hardened toolchain).

Firefox has the "hardened"- and the "jit"-Flag which PaleMoon does not. Here the "hardened"-Flag secures the compatibility to the hardened toolchain while "jit" ist generally incompatible with Hardened

If you could add two similar flags to PaleMoon this would be top-notch

I added the build.log

Thanks ins advance and kind regards
Kalle

**Comment by Kalle72** [comment] 2016-03-04 14:10
Oh pardon the build.log
[build_log.txt](https://github.com/deuiore/palemoon-overlay/files/158773/build_log.txt)

**Comment by vaeth** [comment] 2016-03-04 17:46
I am not the overlay maintainer but another user of hardened and palemoon.

Here it works fine (though I am not using hardened gcc but pass the corresponding *FLAGS "manually").

The palemoon ebuild seems to be well-prepared with hardened (there appear to be the necessary pax-mark commands).

If I read the firefore ebuild correctly, your assumption about USE=hardened in that ebuild is wrong: The only purpose of this flag is to add some LDFLAGS which make the binary more secure even for a <b>non-hardened</b> compiler; on a hardened gcc, this flag has no effect.

palemoon (and firefox) compilation is incompatible with the hardened compiler options -pie and -fPIE; you either have to switch your gcc correspondingly for the compilation of palemoon or pass -no-pie or -fno-PIE (or however these options are called in the hardened toolchain).

Concerning your log, I suppose it does not contain the relevant information: You need to check your grsecurity log which kernel call by which program was actually blocked.

**Comment by Kalle72** [comment] 2016-03-05 12:00
Thanks for the write-up!

Actually I do not read the overlays ebuild, but the gentoo-wiki states "hardened --> Activate default security enhancements for toolchain (gcc, glibc, binutils)". 

On the other hand, compiling firefox works very well for me with hardened toolchain. 

Second, it is relally necessary to have the jit-flag for PaX hardened kernel, because jit does not work with PaX. 

kind regards
Kalle

**Comment by Kalle72** [comment] 2016-03-05 12:03
Pardon again, dmsg told me about the following exec problem:

grsec: denied untrusted exec (due to file in world-writable directory) of /var/tmp/portage/www-client/palemoon-26.1.1/work/palemoon-26.1.1/python/mozbuild/mozbuild/mozconfig_loader by /var/tmp/portage/www-client/palemoon-26.1.1/work/palemoon-26.1.1/python/mozbuild/mozbuild/mozconfig_loader[python2:3365] uid/euid:250/250 gid/egid:250/250, parent /usr/bin/python2.7[python2:3358] uid/euid:250/250 gid/egid:250/250

And again, with the original firefox there is no problem?!?

**Comment by vaeth** [comment] 2016-03-05 15:35
>Second, it is relally necessary to have the jit-flag for PaX hardened kernel, because jit does not work with PaX.

I can just repeat that palemoon works here with PaX. I don't know whether the cause is that it is just allowed by some pax-marking or whether perhaps jit is not even used in palemoon (or perhaps only used in a way which is compatible with pax).

> grsec: denied untrusted exec (due to file in world-writable directory)

Aha: This is due to GRKERNSEC_TPE_ALL=y which is one of the few grsecurity options which I have disabled here because it is too restrictive even for my single-user system.

This is due to the crazy upstream packing of the palemoon tarball which declares all files and directories to have chmod 777. This could be fixed by adding
```
chmod -R go-w "$WORKDIR"
```
to src_prepare in the ebuild.

(BTW, shouldn't epatch_user be the last command in src_prepare?)

**Comment by Kalle72** [comment] 2016-03-05 20:04
Thanks again,

I changed the ebuild a little bit (added chmod -R go-w "$WORKDIR" and a jit-flag) and now it works very well. 

Therefore I would suggest to the maintainer of the overlay to include this for hardening users.

By the way, three lines over the inserted " chmod -R go-w "$WORKDIR" " there is another chmod line. Eventually one can change this line with the same result?!

 To the "epatch_user" thing: I have no clue ;-)

**Comment by Kalle72** [comment] 2016-03-05 20:24
Fortgot to post my ebuild. 

Just another short remark: I disabled jit with a useflag. It seems to me that the original gentoo-firefox-ebuild uses another approach. Here jit is enabled, but the binaries build are marked with the "m" PaxFlag. I think this approach is also applicable. 

[palemoon-26.1.1.ebuild.txt](https://github.com/deuiore/palemoon-overlay/files/160008/palemoon-26.1.1.ebuild.txt)

**Comment by deuiore** [comment] 2016-04-01 16:43
@Kalle72
>Just another short remark: I disabled jit with a useflag.

I don't think that's going to do anything. There is no `--disable-jit` option listed in Pale Moon's [`configure.in`](http://xref.palemoon.org/palemoon-rel26/source/configure.in).

**Comment by Kalle72** [comment] 2016-04-03 09:54
Thanks for your answer!

You seem to be right! I copied it from another overlay providing an older version of Palemoon. 

I tested the ebuild again adding only with the <<chmod -R go-w "$WORKDIR">>-thing mentioned by vaeth and it works. So to sum up I would suggest to add <<chmod -R go-w "$WORKDIR">> then it should also work on hardened. 

Best regards Kalle

PS: Is there any plan to include FossaMail in this overlay?

**Comment by deuiore** [comment] 2016-04-03 21:22
The "<>-thing"?
If you're talking about fixing the file permissions, I did that in the [last commit](https://github.com/deuiore/palemoon-overlay/commit/0b461b4761734aa584c547cb5ab1e7a4296cfe36). Could you try updating the overlay and see if that works for you?

**Comment by Kalle72** [comment] 2016-04-04 10:04
Oh nice, it works!!! Thanks a lot. 

Unfortunately one problem remains. During the emerge-process the download of the german language pack brings an checksum error into play (I tested also the hungarian Language pack which works). My output:
---------------------------------------------------
>>> Downloading 'http://relmirror.palemoon.org/langpacks/26.x/de.xpi'
--2016-04-04 12:00:08--  http://relmirror.palemoon.org/langpacks/26.x/de.xpi
Resolving relmirror.palemoon.org (relmirror.palemoon.org)... 31.7.184.106
Connecting to relmirror.palemoon.org (relmirror.palemoon.org)|31.7.184.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 385676 (377K) [application/x-xpinstall]
Saving to: ‘/usr/portage/distfiles/palemoon-26.1.1-de.xpi’

/usr/portage/distfi 100%[=====================>] 376,64K   911KB/s   in 0,4s   

2016-04-04 12:00:08 (911 KB/s) - ‘/usr/portage/distfiles/palemoon-26.1.1-de.xpi’ saved [385676/385676]

!!! Fetched file: palemoon-26.1.1-de.xpi VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      385676
!!! Expected: 385675
Refetching... File renamed to '/usr/portage/distfiles/palemoon-26.1.1-de.xpi._checksum_failure_.cisjx_qu'

!!! Couldn't download 'palemoon-26.1.1-de.xpi'. Aborting.
 * Fetch failed for 'www-client/palemoon-26.1.1-r1', Log file:
 *  '/var/tmp/portage/www-client/palemoon-26.1.1-r1/temp/build.log'

>>> Failed to emerge www-client/palemoon-26.1.1-r1, Log file:

>>>  '/var/tmp/portage/www-client/palemoon-26.1.1-r1/temp/build.log'

 * Messages for package www-client/palemoon-26.1.1-r1:

 * Fetch failed for 'www-client/palemoon-26.1.1-r1', Log file:
 *  '/var/tmp/portage/www-client/palemoon-26.1.1-r1/temp/build.log'
--------------------------------------------------------------
Is this a problem of the ebuild or from the palemoon language-pack?

Best regards Kalle

**Comment by Kalle72** [comment] 2016-04-04 10:07
Sorry for the huge script-size. Don't know why it occurs??? Seems to be related to two ---- lines I included to separate my output.

**Comment by deuiore** [comment] 2016-04-04 17:54
Apparently those and some other language files have been modified from when their checksum and file size was added to the Manifest, hence the error you're seeing.
I re-downloaded and re-checked everything and updated the Manifest. Now it should work.

Next time please open another Issue if you're reporting an unrelated problem.

**Comment by Kalle72** [comment] 2016-04-04 19:27
Thanks a lot!!!

**Closed** 2016-04-05 09:05 UTC
