### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by japanoise** [deuiore/palemoon-overlay#28] opened 2016-07-20 20:59 UTC
If dev-libs/nss is unmerged and palemoon is already installed you'll get this warning from emerge:

```
!!! existing preserved libs:
>>> package: dev-libs/nss-3.23
 *  - /usr/lib64/libnss3.so
 *      used by /usr/lib64/palemoon/libsmime3.so (www-client/palemoon-26.3.3)
 *      used by /usr/lib64/palemoon/libssl3.so (www-client/palemoon-26.3.3)
 *      used by /usr/lib64/palemoon/libxul.so (www-client/palemoon-26.3.3)
 *  - /usr/lib64/libssl3.so
 *      used by /usr/lib64/palemoon/libxul.so (www-client/palemoon-26.3.3)
 *  - /usr/lib64/libnssutil3.so
 *      used by /usr/lib64/palemoon/libfreebl3.so (www-client/palemoon-26.3.3)
 *      used by /usr/lib64/palemoon/libnss3.so (www-client/palemoon-26.3.3)
 *      used by /usr/lib64/palemoon/libnssdbm3.so (www-client/palemoon-26.3.3)
 *      used by 4 other files
 *  - /usr/lib64/libsmime3.so
 *      used by /usr/lib64/palemoon/libxul.so (www-client/palemoon-26.3.3)
```

Installing nss fixes the issue, so it is a dependency, Please add nss as a dependency for palemoon.

**Comment by Khayyam** [comment] 2016-12-03 18:26
japanoise ... dev-libs/nss may not be a dependency, it is just that palemoon links against it (rather than the nss bundled with palemoon). I assume that is the case as some are building without dev-libs/nss being installed (and so without the preserved-lib). See my additional comment in the 'revdep-rebuild' bug.

**Comment by deuiore** [comment] 2017-02-16 13:41
Duplicate of #19.

**Closed by deuiore** 2017-02-16 13:41 UTC
