### ISSUE TITLE
palemoon-27.0.3-r1 fails configure: cannot determine icu version number from uvernum.h header file

### ISSUE THREAD

**Issue by kentfredric** [deuiore/palemoon-overlay#36] opened 2017-02-17 01:08 UTC
Unrelated to my other bug as it happens even with a properly switched GCC:4.9.4

```
 0:51.81 checking for posix_fadvise... yes
 0:51.94 checking for posix_fallocate... yes
 0:52.20 sed: character class syntax is [[:space:]], not [:space:]
 0:52.20 configure: error: cannot determine icu version number from uvernum.h header file
 0:52.20 ------ config.log ------
 0:52.20 configure:26027: checking for fontconfig
 0:52.20 configure:26034: checking _FONTCONFIG_CFLAGS
 0:52.20 configure:26039: checking _FONTCONFIG_LIBS
 0:52.20 configure:26238: checking for stdint.h
 0:52.20 configure:26251: gcc -c -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe  conftest.c 1>&5
 0:52.20 configure:26238: checking for inttypes.h
 0:52.20 configure:26251: gcc -c -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe  conftest.c 1>&5
 0:52.20 configure:26238: checking for sys/int_types.h
 0:52.20 configure:26251: gcc -c -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe  conftest.c 1>&5
 0:52.20 configure:26245:27: fatal error: sys/int_types.h: No such file or directory
 0:52.20 compilation terminated.
 0:52.20 configure: failed program was:
 0:52.20 #line 26243 "configure"
 0:52.20 #include "confdefs.h"
 0:52.20 
 0:52.20 #include <sys/int_types.h>
 0:52.20 int main() {
 0:52.20 
 0:52.20 ; return 0; }
 0:52.20 configure:27651: checking for posix_fadvise
 0:52.20 configure:27683: gcc -o conftest -Wall -Wdeclaration-after-statement -Wempty-body -Wpointer-to-int-cast -Wsign-compare -Wtype-limits -Wno-unused -Wcast-align -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe  -lpthread -Wl,-O1 -Wl,--as-needed -Wl,-z,noexecstack -Wl,-z,text -Wl,--build-id -B /var/tmp/portage/www-client/palemoon-27.0.3-r1/work/palemoon-27.0.3/obj-x86_64-unknown-linux-gnu/build/unix/gold conftest.c -ldl  1>&5
 0:52.20 configure:27651: checking for posix_fallocate
 0:52.20 configure:27683: gcc -o conftest -Wall -Wdeclaration-after-statement -Wempty-body -Wpointer-to-int-cast -Wsign-compare -Wtype-limits -Wno-unused -Wcast-align -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe  -lpthread -Wl,-O1 -Wl,--as-needed -Wl,-z,noexecstack -Wl,-z,text -Wl,--build-id -B /var/tmp/portage/www-client/palemoon-27.0.3-r1/work/palemoon-27.0.3/obj-x86_64-unknown-linux-gnu/build/unix/gold conftest.c -ldl  1>&5
 0:52.20 configure:27737: gcc -c -Wall -Wdeclaration-after-statement -Wempty-body -Wpointer-to-int-cast -Wsign-compare -Wtype-limits -Wno-unused -Wcast-align -pipe -mtune=native -march=native -std=gnu99 -fgnu89-inline -fno-strict-aliasing -fno-math-errno -pthread -pipe   conftest.c 1>&5
 0:52.21 configure: error: cannot determine icu version number from uvernum.h header file
 0:52.21 *** Fix above errors and then restart with\
 0:52.21                "/usr/bin/gmake -f client.mk build"
 0:52.21 gmake: *** [client.mk:363: configure] Error 1

```

**Comment by deuiore** [comment] 2017-02-17 01:37
That's another issue. It's caused by sed-4.3 (which now you've probably updated to) requiring a stricter syntax. It was fixed by Pale Moon in 27.1.0, so you should probably try the palemoon-27.1.0 ebuild.

**Closed** 2017-03-23 21:29 UTC
